#!/usr/bin/env bash
#
# Turns a flight sheet into arguments for the miner.
#
# DeroStorm is a solo miner: it speaks derod's getwork, so the flight sheet's
# "Pool URL" is the address of a derod node and the wallet is the address a
# found block pays. There is no pool account, no worker name and no pool share
# accounting, which is why nothing here looks for one.

[[ -t 1 ]] && . colors

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
. h-manifest.conf

# The wallet. HiveOS substitutes %WAL% into the template before we see it, so
# CUSTOM_TEMPLATE is normally already the address.
WALLET="$CUSTOM_TEMPLATE"

# The node. A flight sheet URL may carry a scheme and a path that derod's
# getwork does not want, so host:port is taken out of whatever was typed.
NODE="$CUSTOM_URL"
NODE="${NODE#*://}"       # drop stratum+tcp://, http://, and friends
NODE="${NODE%%/*}"        # drop any path
[[ -z "$NODE" ]] && NODE="127.0.0.1:10100"
[[ "$NODE" != *:* ]] && NODE="$NODE:10100"

# Everything in "Extra config arguments" is passed through verbatim, so every
# flag the miner has is reachable from the flight sheet without this wrapper
# needing to know about it: --mining-threads, --gpu, --gpu-blocks, --testnet,
# and the rest. One per line or all on one line, both work.
#
# The echo is deliberately unquoted: word splitting is what collapses the
# newlines and runs of spaces into single spaces and trims the ends, which a
# quoted echo would not do.
EXTRA=$(echo $CUSTOM_USER_CONFIG)

conf="$(pwd)/$CUSTOM_CONFIG_FILENAME"
cat > "$conf" <<CONF
# Generated by h-config.sh from the flight sheet. Edits are lost on the next
# flight sheet change; put them in "Extra config arguments" instead.
DEROSTORM_NODE="$NODE"
DEROSTORM_WALLET="$WALLET"
DEROSTORM_EXTRA="$EXTRA"
CONF

echo "derostorm: node $NODE"
if [[ -n "$WALLET" ]]; then
  echo "derostorm: wallet ${WALLET:0:12}...${WALLET: -6}"
else
  echo "derostorm: WARNING - no wallet in the flight sheet"
fi
[[ -n "$EXTRA" ]] && echo "derostorm: extra $EXTRA"
exit 0
