#!/usr/bin/env bash
#
# Turns a flight sheet into arguments for the miner.
#
# DeroStorm is a solo miner: it speaks derod's getwork, so the flight sheet's
# "Pool URL" is the address of a derod node and the wallet is the address a
# found block pays. There is no pool account, no worker name and no pool share
# accounting, which is why nothing here looks for one.

[[ -t 1 ]] && . colors

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
. h-manifest.conf

# The wallet. HiveOS substitutes %WAL% into the template before we see it, so
# CUSTOM_TEMPLATE is normally already the address.
WALLET="$CUSTOM_TEMPLATE"

# The node. A flight sheet URL may carry a scheme and a path that derod's
# getwork does not want, so host:port is taken out of whatever was typed.
NODE="$CUSTOM_URL"
NODE="${NODE#*://}"       # drop stratum+tcp://, http://, and friends
NODE="${NODE%%/*}"        # drop any path
[[ -z "$NODE" ]] && NODE="127.0.0.1:10100"
[[ "$NODE" != *:* ]] && NODE="$NODE:10100"

# Everything in "Extra config arguments" is passed through verbatim, so every
# flag the miner has is reachable from the flight sheet without this wrapper
# needing to know about it: --mining-threads, --gpu, --gpu-blocks, --testnet,
# and the rest. One per line or all on one line, both work.
#
# The echo is deliberately unquoted: word splitting is what collapses the
# newlines and runs of spaces into single spaces and trims the ends, which a
# quoted echo would not do.
EXTRA=$(echo $CUSTOM_USER_CONFIG)

# CPU threads, if the flight sheet did not say.
#
# The miner's own default is "logical CPUs minus one", which is right for a
# desktop and wrong for a rig. A rig is usually a cheap processor carrying a lot
# of cards, and every GPU needs a host thread to feed it: DeroStorm's own
# measurements show a CPU miner competing with that feeder costs more than it
# earns, and on a rig the GPUs are effectively all of the hashrate. Four threads
# and six cards should not be running three CPU miners.
#
# So: one thread per logical CPU, minus one for each card, minus one for the
# rest of the system, and never below one. On a 4-thread rig with six GPUs that
# is 1; on a 16-thread box with one card it is 14, which is where this miner's
# own sweep put the optimum.
#
# Put --mining-threads in "Extra config arguments" to override it.
if [[ "$EXTRA" != *--mining-threads* ]]; then
  NCPU=$(nproc 2>/dev/null || echo 2)

  # How many cards will actually be fed, which is not always how many are
  # present. --gpu=off means none of them, and --gpu=0,1 on a six-card rig means
  # two. Reserving a thread per installed card in either case gave away CPU
  # threads to feeders that were never going to exist.
  case "$EXTRA" in
    *--gpu=off*|*--gpu=none*|*--gpu=no*)
      NGPU=0 ;;
    *--gpu=all*|*)
      NGPU=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | grep -c .) ;;
  esac
  if [[ "$EXTRA" =~ --gpu=([0-9]+(,[0-9]+)*) ]]; then
    NGPU=$(echo "${BASH_REMATCH[1]}" | tr ',' '
' | grep -c .)
  fi
  [[ -z "$NGPU" ]] && NGPU=0
  # The miner tops out at 16 devices; see maxGPUs in cmd/derostorm/gpu_worker.go.
  (( NGPU > 16 )) && NGPU=16

  THREADS=$(( NCPU - NGPU - 1 ))
  (( THREADS < 1 )) && THREADS=1
  EXTRA="$EXTRA --mining-threads=$THREADS"
  THREADNOTE=" (${NCPU} CPUs, ${NGPU} GPUs fed)"
fi

conf="$(pwd)/$CUSTOM_CONFIG_FILENAME"
cat > "$conf" <<CONF
# Generated by h-config.sh from the flight sheet. Edits are lost on the next
# flight sheet change; put them in "Extra config arguments" instead.
DEROSTORM_NODE="$NODE"
DEROSTORM_WALLET="$WALLET"
DEROSTORM_EXTRA="$EXTRA"
CONF

echo "derostorm: node $NODE"
if [[ -n "$WALLET" ]]; then
  echo "derostorm: wallet ${WALLET:0:12}...${WALLET: -6}"
else
  echo "derostorm: WARNING - no wallet in the flight sheet, the miner will refuse to start"
fi
echo "derostorm: args$THREADNOTE $EXTRA"
exit 0
